### ISSUE TITLE
Working with other fringe (ex git-gutter)

### ISSUE THREAD

**Issue by aadi58002** [emacs-tree-sitter/treesit-fold#16]
Provide a example of how to use fringe indicator with other fringe like git-gutter.

Honestly would prefer if there is a way to have both of the fringes on the left side.

PS: thanks for the great package.

**Comment by jcs090218** [comment]
There is no way to use multiple fringes at the same spot, but you can change the fringe color from this package to make it look nicer.

See the bottom of this section https://github.com/emacs-tree-sitter/treesit-fold?tab=readme-ov-file#-usage-1. It describes how this package works with the `line-reminder` package, and you can do the same with `git-gutter` or other similar packages.
