### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by garyo** [emacs-tree-sitter/treesit-fold#2]
Just to confirm, is the starting (current) state of this repo the same as master branch of https://github.com/emacs-tree-sitter/ts-fold? Have any changes been made yet beyond that? I notice it still depends on `tree-sitter` and if I understand the point, it should only use built-in `treesit`. I can help with some of this if needed. I presume the first thing will be to merge in @AndrewSwerlick 's changes?

**Comment by jcs090218** [comment]
Yes, it is currently aligned with the master branch of ts-fold.

This is the official repository for those interested in treesit.el support. Given the past interest from various individuals, they are now welcome to submit pull requests to this repository, which will be reviewed and merged. 🤔

Ping people who might be interested in this, @AndrewSwerlick, @abougouffa, @DevelopmentCool2449. :)

**Comment by DevelopmentCool2449** [comment]
Jen-Chieh Shen ***@***.***> writes:

> Yes, it is currently aligned with the master branch of ts-fold.
>
> This is the official repository for those interested in treesit.el support. Given the past interest from various individuals, they are now
> welcome to submit pull requests to this repository, which will be reviewed and merged. 🤔
>
> Ping people who might be interested in this, @AndrewSwerlick, @abougouffa, @DevelopmentCool2449. :)

Thank you, i will open a PR when i can for bring some features from
@abougouffa fork.

**Comment by DevelopmentCool2449** [comment]
I've opened a [PR](https://github.com/emacs-tree-sitter/treesit-fold/pull/3) for treesit support

**Comment by jcs090218** [comment]
Everything is all set. Close this issue now. :)
